name: CI for pull requests (exporter/mackerelotlpexporter)

on:
  pull_request:
    paths:
      - exporter/mackerelotlpexporter/**
      - .github/workflows/on-pull-request-mackerelotlpexporter.yml
      - .github/workflows/wf-test-golib.yml

jobs:
  test:
    uses: ./.github/workflows/wf-test-golib.yml
    with:
      working-directory: exporter/mackerelotlpexporter
