name: CI for pull requests (distributions/otelcol-mackerel)

on:
  pull_request:
    paths:
      - go.mod
      - go.mod
      - distributions/otelcol-mackerel/**
      - exporter/mackerelotlpexporter/**
      - confmap/provider/zerocfgprovider/**
      - .github/workflows/on-pull-request-otelcolmackerel.yml
      - .github/workflows/wf-test-otelcolmackerel.yml

jobs:
  test:
    uses: ./.github/workflows/wf-test-otelcolmackerel.yml
