name: CI for pull requests (confmap/provider/zerocfgprovider)

on:
  pull_request:
    paths:
      - confmap/provider/zerocfgprovider/**
      - .github/workflows/on-pull-request-zerocfgprovider.yml
      - .github/workflows/wf-test-golib.yml

jobs:
  test:
    uses: ./.github/workflows/wf-test-golib.yml
    with:
      working-directory: confmap/provider/zerocfgprovider
