name: test all Go library modules

on:
  workflow_call:
    inputs:
      go-cache:
        type: boolean
        default: false

jobs:
  lint:
    strategy:
      matrix: &test_all_golibs_matrix
        go-version: [stable, oldstable]
        os: [ubuntu-latest]
        working-directory:
          - exporter/mackerelotlpexporter
          - confmap/provider/zerocfgprovider
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: ${{ inputs.go-cache }}
          working-directory: ${{ matrix.working-directory }}
      - uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9.0.0
        with:
          args: --timeout=10m
          working-directory: ${{ matrix.working-directory }}

  test:
    strategy:
      matrix: *test_all_golibs_matrix
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: ${{ inputs.go-cache }}
          working-directory: ${{ matrix.working-directory }}
      - name: Run Go tests
        run: |
          set -o pipefail
          go test ./... -cover -json > ./go-test.out
        working-directory: ${{ matrix.working-directory }}
      - name: Format test result
        if: always()
        run: |
          go tool tparse -all -file ./go-test.out
          go tool tparse -all -file ./go-test.out -format markdown >> "$GITHUB_STEP_SUMMARY"
        working-directory: ${{ matrix.working-directory }}
